version: "3.3"

services:
  backend:
    image: django_backend
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - $HOME/code/squash/squash/backend/squash:/app/
    ports:
      - 8000:8000
    depends_on: 
      - db

  db: 
    image: postgres
    container_name: postgres_database
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports: 
      - 80:80
    depends_on: 
      - backend

volumes:
  postgres_data:
