# Generated by Django 3.1.3 on 2020-11-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-win_matches_count']},
        ),
    ]
