# Generated by Django 3.1.3 on 2020-11-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20201129_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='player_1',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='player_2',
            new_name='opponent',
        ),
    ]
