# Generated by Django 3.1.3 on 2020-11-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_auto_20201130_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='player_1_sets',
            new_name='creator_sets',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='player_2_sets',
            new_name='opponent_sets',
        ),
    ]
