# Generated by Django 3.1.3 on 2020-11-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_auto_20201130_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
    ]
